package net.macu.UI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import net.macu.core.Pipeline;
import net.macu.cutter.ConstantHeightCutter;
import net.macu.disk.MultiScanSaver;
import net.macu.settings.L;

import javax.swing.*;
import java.awt.*;

public class ConstantHeightForm implements Form {
    private JLabel filePathLabel;
    private JTextField filePathTextField;
    private JButton browseButton;
    private JLabel heightLabel;
    private JTextField heightTextField;
    private JPanel form;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public ConstantHeightForm() {
        browseButton.addActionListener(e -> {
            String path = ViewManager.requestChooseDir(null);
            filePathTextField.setText(path);
        });
        filePathLabel.setText(L.get("UI.ConstantHeightForm.path_label"));
        browseButton.setText(L.get("UI.ConstantHeightForm.browse_button"));
        heightLabel.setText(L.get("UI.ConstantHeightForm.height_label"));
    }

    @Override
    public boolean validateInput() {
        String path = filePathTextField.getText();
        if (path.isEmpty()) {
            ViewManager.showMessageDialog("UI.ConstantHeightForm.validateInput.empty_path", null);
            return false;
        }
        try {
            if (Integer.parseInt(heightTextField.getText()) <= 0) {
                ViewManager.showMessageDialog("UI.ConstantHeightForm.validateInput.positive_height", null);
            }
        } catch (NumberFormatException e) {
            ViewManager.showMessageDialog("UI.ConstantHeightForm.validateInput.nan_height", null);
        }
        return true;
    }

    @Override
    public JComponent getRootComponent() {
        return $$$getRootComponent$$$();
    }

    public String getDescription() {
        return L.get("UI.ConstantHeightForm.description");
    }

    @Override
    public Pipeline getConfiguredPipeline() {
        return new Pipeline(new ConstantHeightCutter(Integer.parseInt(heightTextField.getText())), new MultiScanSaver(filePathTextField.getText()));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        form = new JPanel();
        form.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        form.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        filePathLabel = new JLabel();
        filePathLabel.setText("Save in:");
        panel1.add(filePathLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        filePathTextField = new JTextField();
        panel1.add(filePathTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        browseButton = new JButton();
        browseButton.setText("Browse");
        panel1.add(browseButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        form.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        heightLabel = new JLabel();
        heightLabel.setText("Height:");
        panel2.add(heightLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        heightTextField = new JTextField();
        panel2.add(heightTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return form;
    }
}
